### ISSUE TITLE
Read `scarb-version` from `.tool-versions`

### ISSUE THREAD

**Issue by delaaxe** [software-mansion/setup-scarb#5]
### Problem

Better to avoid having the scarb version repeated across many places

### Proposed Solution

Something like this:

```
      - name: Getting scarb
        uses: software-mansion/setup-scarb@v1
        with:
          scarb-version: from-tool-versions
```

`/.tool-versions` in the repo:

```
scarb 0.5.2
```
